insert into credential_manager values (101, 'hmk@gmail.com', 'harsh123','harsh' )
insert into credential_manager values (102, 'ved@gmail.com', 'ved123', 'vedika')
insert into credential_manager values (103, 'pur@gmail.com', 'pur123', 'Purvi')
insert into credential_manager values (104, 'daya@gmail.com', 'daya123', 'Daya')
insert into credential_manager values (105, 'acp@gmail.com', 'acp123', 'ACP')