insert into alien values (101,'Harsh','Android')
insert into alien values (102,'Vedika','Java')
insert into alien values (103,'Mahesh','C++')
insert into alien values (104,'Rohit','Ruby')
insert into alien values (105,'Mandar','Node.js')